ximu3/vnite

package-lock.json
src/renderer/src/components/AddGame.jsx

Fixes #73 
该修复只是简单的类型转换
建议将来将带 `ga` 的gid字符串和不带 `ga` 的数值分成两个变量处理

Ensure that the gid is a string when submitted

---

src/main/scraper/vndb/common.ts

修改了使用vndb api标题搜索的逻辑，修复使用其它数据源时Screenshots数据与游戏不匹配的问题。
与 #76 的第2项修复相似。

Fix search with title when using vndb api

---

src/renderer/src/components/Game/Config/AttributesDialog/main.tsx
src/renderer/src/components/Game/Config/CollectionMenu/main.tsx
src/renderer/src/components/Game/Config/main.tsx
src/renderer/src/components/Librarybar/GameNav.tsx
src/renderer/src/components/Showcase/posters/BigGamePoster.tsx
src/renderer/src/components/Showcase/posters/GamePoster.tsx
src/renderer/src/components/contextMenu/GameNavCM/CollectionMenu.tsx
src/renderer/src/components/contextMenu/GameNavCM/main.tsx
src/renderer/src/components/dialog/AddCollectionDialog.tsx

右键菜单选择行为（如新收藏或属性）后不会主动消失。
PS.
感觉右键菜单和弹出的页面耦合度过高，完全修改比较麻烦。
本次提交没有修改大结构和目录，只是将弹出的界面提高到了与右键菜单的同一层并传递信号函数。
或许之后能以此为基础完全解耦吧）

Auto close ContextMenu for addCollection and Attributes

---

src/renderer/src/components/Game/Header.tsx
src/renderer/src/components/Showcase/posters/CollectionPoster.tsx
src/renderer/src/components/contextMenu/CollectionCM/main.tsx
src/renderer/src/pages/GameBatchAdder/GameList.tsx
src/renderer/src/pages/GameBatchAdder/GameListTable.tsx

1. 修复了小尺寸界面下的批量刮削页面显示不全的问题
2. 修复了小尺寸界面下游戏页面的 `Header` 显示不全的问题
3. 修复了 `CollectionPoster` 右键菜单失效的问题
4. 使用原名作为收藏重命名的初值，同时增加取消按钮

Some fixes

---

package-lock.json
src/renderer/src/components/Game/Config/ManageMenu/NameEditorDialog.tsx
src/renderer/src/components/Game/Header.tsx
src/renderer/src/components/contextMenu/CollectionCM/main.tsx
src/renderer/src/components/dialog/AddCollectionDialog.tsx
src/renderer/src/pages/GameAdder/ScreenshotList.tsx
src/renderer/src/pages/GameAdder/Search.tsx
src/renderer/src/pages/GameAdder/main.tsx

为vnite添加快捷键
已完成：
- 为刮削器添加游戏时游戏名称、id的编辑使用 `Enter` 作为快捷键
- 为创建新收藏、重命名收藏时的编辑使用 `Enter` 作为快捷键
- 为重命名游戏、为游戏评分使用 `Enter` 作为快捷键
- 为确定游戏截图时使用 `Enter` 作为快捷键
- 刮削器默认聚焦至游戏名称输入框
- 为刮削器搜索时输入框的切换使用 `ArrowUp` 和 `ArrowDown` 作为快捷键
- 为切换选择的游戏截图时使用 `Arrow` 作为快捷键

Add ShortCutKeys to Vnite

---

package-lock.json
src/renderer/src/pages/GameAdder/GameList.tsx
src/renderer/src/pages/GameAdder/Search.tsx
src/renderer/src/pages/GameAdder/store.ts

- 使用刮削器添加游戏时，通过按住某个键（如Backspace）进行输入时，输入卡顿严重
1. 在 `Search` 中使用局部状态变量，避免了输入时频繁的全局状态修改导致卡顿
2. 移除了 `Search` 中无用的try-catch，其只能捕获几乎不可能发生的异常
3. 调整了 `GameList` 的滚动框大小，使得其随 `vh` 线性变化并填满卡片
4. 移动了 `type GameList` 的位置以复用该类型
~一到期末平时存硬盘里都不想玩的gal突然就变得好玩起来了(ヾ;￣▽￣)ヾ~

Smoother GameAdderSearcher

---

src/renderer/src/components/Game/Header.tsx
src/renderer/src/utils/formatter.ts

1. 未评分的游戏打开评分界面将显示空输入框
2. 输入为空时确认评分为清除评分
3. 阻止了负数评分
4. 修复了原先代码中的一个小问题
https://github.com/ximu3/vnite/blob/50ab868ee8cbb9805767e5d3e4a9232730a27e48/src/renderer/src/components/Game/Header.tsx#L63-L71
如 `scoreNum` 为 9.999 时会 `preScore` 会是 10.0 而非 10

Optimize Score

---

src/renderer/src/components/Librarybar/GameNav.tsx
src/renderer/src/components/Librarybar/main.tsx

对批量编辑的功能稍微改了一点点
1. 在某个游戏的详情页时，阻止将该游戏移除批量选中列表
2. 被选中批量的游戏在仅有一个时也会显示而不是凑齐两个再显示
3. 跳转到非游戏详情页时，如果不处于批量编辑模式（选中两个以上游戏），清空批量选中列表

Optimize the BatchEditor

---

src/main/adder/common.ts
src/main/database/save.ts
src/main/database/services.ts
src/main/ipc/utils.ts
src/main/monitor/common.ts
src/main/utils/dialog.ts
src/renderer/src/components/Game/Config/AttributesDialog/Path/main.tsx
src/renderer/src/components/Game/Save/main.tsx

- **修改了`path.json`的结构**
- 移除了与存档类型相关的字段
- 增加了`version`字段，增加了原结构json文件向新结构json文件升级的逻辑
- 增加了`savePathInDB`字段，用于适应同时追踪多个相同名称的文件/文件夹的情形（使用数字前缀）
> 虽然感觉几乎不会有这种情形
- **修改了属性设置界面路径栏**
- 移除了存档类型的选项卡，同时追踪文件与文件夹
- 添加文件夹与添加文件两个按钮同时存在，并且向存档路径输入框中增量更新
- 增加了按钮的悬停提示文本，修改了按钮图标
- 对于选择文件夹与选择文件窗口，将gamePath的父目录作为选择窗口的起始路径
目前是直接在`getDBValue`里加了一段检查版本并触发更新的逻辑，同时添加了一个`withoutchek`的参数用来关闭检查功能（因为更新逻辑的内部同样调用了`getDBValue`。
**相关issu**e：#126

Support mixed types of save backups

---

src/renderer/src/components/Showcase/posters/BigGamePoster.tsx
src/renderer/src/components/Showcase/posters/GamePoster.tsx

在海报墙的页面，鼠标移动到某个游戏上时显示的悬浮窗会遮挡住旁边的游戏，如果想显示被挡住的游戏的悬浮窗，只能把鼠标移到其他地方等待悬浮窗消失后再移动回来。

Optimized the display of the poster wall

---

src/renderer/src/components/Showcase/posters/BigGamePoster.tsx
src/renderer/src/components/Showcase/posters/GamePoster.tsx

原先在悬浮窗上光标样式是默认的箭头光标，在光标由一个游戏向被悬浮窗挡住的下一个游戏移动时，会出现一次快速的样式变化，这个快速的闪烁体验有些不好。

Optimized the cursor of the poster wall

---

src/renderer/src/hooks/records.ts

记录页面的近一年游戏时间图表，在凌晨时显示的日期标签整体前移了一天。

Fixed a time zone issue in the yearly records

---

src/renderer/src/components/Game/Config/AttributesDialog/Media/UrlDialog.tsx
src/renderer/src/components/Game/Config/AttributesDialog/Media/main.tsx

属性-媒体-从链接获取图片的对话框，在产生内容更新时，会触发父组件的渲染，从而导致对话框闪烁（消失又出现）。

Resolve issue with URL input dialog flickering on update

---

package-lock.json
package.json
src/renderer/src/components/Showcase/posters/CollectionPoster.tsx
src/renderer/src/components/ui/drop-indicator.tsx
src/renderer/src/hooks/collections.ts

- 引入了`Pragmatic drag and drop`用于支持拖拽相关功能
- 实现了在主页通过拖动收藏夹图标进行重新排序的功能
- 正式版本中，主页的收藏夹栏的左右滚动条并没有作用（图1），因此不确定这种拖拽对于左右滚动条的适应性如何
- 宽封面时的收藏夹图片存在黑边（同图1）

Support drag-and-drop sorting of collections

---

src/renderer/src/components/Game/Header.tsx
src/renderer/src/components/Game/Overview/Information/InformationCard.tsx
src/renderer/src/components/Game/Overview/Information/InformationDialog.tsx
src/renderer/src/components/Game/Overview/RelatedSites/RelatedSitesCard.tsx
src/renderer/src/components/Game/Overview/Tags/TagsCard.tsx
src/renderer/src/components/Game/Overview/description/DescriptionCard.tsx

主要对游戏详情页做了一些优化：
- 增加了点击游戏名、简介、基本信息、相关站点、标签后，自动将其复制到剪切板的功能
- 在基本信息栏中加入了“译名”一项
- 阻止了若干不必要的文本选取

Optimize the text selection on the game overview page

---

src/renderer/src/components/Config/Appearances.tsx
src/renderer/src/components/Librarybar/GameNav.tsx
src/renderer/src/components/Librarybar/main.tsx
src/renderer/src/components/ui/nav.tsx

本地游戏标识：
- 增加了在列表右侧使用图标标识本地游戏的功能
- 开启高亮本地游戏时，选中某一游戏只改变背景颜色，不改变文本颜色，避免本地游戏高亮与选中高亮混淆
游戏列表中的选中游戏高亮：
从主页点击游戏时，边栏中对应游戏项可能无法正确高亮。比如所有游戏一栏中的对应游戏能够高亮，但是上面的按游戏状态分类中的对应项没有高亮。同时快速定位按钮会定位到排列靠前的对应游戏，所以总是定位到按游戏状态分类里面那个没有被高亮的项目。
其他：
- 增加了不按任何分组显示游戏的选项

Optimize the highlighting of the game list

---

src/renderer/src/components/Showcase/CollectionGames.tsx
src/renderer/src/components/Showcase/CollectionPage.tsx
src/renderer/src/components/Showcase/Collections.tsx
src/renderer/src/components/Showcase/posters/CollectionPoster.tsx
src/renderer/src/components/Showcase/posters/GamePoster.tsx

- 动态计算拖拽提示器的位置，保证在间距变化时仍在正中间显示
- 对于左右两侧的元素，为避免提示器渲染到可视区域外，使用更小的渲染偏移

Adapt the drop indicator to the grid layout

---

src/renderer/src/components/Game/Config/ManageMenu/NameEditorDialog.tsx
src/renderer/src/components/Game/Config/ManageMenu/PlayingTimeEditorDialog.tsx
src/renderer/src/components/Game/Config/ManageMenu/main.tsx
src/renderer/src/components/Game/Config/main.tsx
src/renderer/src/components/Librarybar/GameNav.tsx
src/renderer/src/components/Showcase/posters/BigGamePoster.tsx
src/renderer/src/components/Showcase/posters/GamePoster.tsx
src/renderer/src/components/contextMenu/GameNavCM/ManageMenu.tsx
src/renderer/src/components/contextMenu/GameNavCM/main.tsx

优化了修改游戏时间 / 修改游戏名的对话框：
- 点击对话框以外的部分可以关闭对话框
> 添加属性 onOpenChange={setIsOpen}
- 点击下拉菜单 / 右键菜单中的选项打开对话框后，不会残留下拉菜单 / 右键菜单

Optimized the experience of the context/drop-down menu of game Config

---

src/renderer/src/components/ui/button.tsx
src/renderer/src/pages/Record/MonthlyReport.tsx

修复若干月度报告日历中日期的不正确标记：
- 当前日期会被高亮标记
- 切换到其他月份时，1号会被高亮标记
- 存在游玩记录的日期高亮标记整体后移了一天
另外，把月份范围外的日期隐藏了
> 原先的变淡总感觉对比不够强

fix: Fixed date rendering error in monthly report calendar

---

src/renderer/src/components/Game/Record/TimerChart.tsx
src/renderer/src/utils/i18n.ts

若某一天的游戏时间小于30s，游戏的记录页面的柱状图中会因为四舍五入而将其忽略掉，而在其他使用毫秒计算的函数中又会将该天视作有游戏记录，导致了不一致的数据表现。
因此去掉了这个图表数据源处理时的round函数，同时修改了格式化工具，将小于30s的时间格式化为 '<1min'。

fix: game time under 30s not displaying correctly on the game's record page

---

src/renderer/src/components/Librarybar/GameList/AllGame.tsx
src/renderer/src/components/Librarybar/GameList/FilterGame.tsx
src/renderer/src/components/Librarybar/GameList/Others.tsx
src/renderer/src/components/Librarybar/GameList/Search.tsx
src/renderer/src/components/Librarybar/main.tsx
src/renderer/src/stores/game/gameUtils.ts

- 把原先侧栏中`所有游戏`右键开启的排序方式设置窗口移动到了外面
- 把这个排序应用到了筛选、查询、按游戏状态/类型/开发商分组的游戏展示中，共用一套设置
- 考虑到收藏夹内部游戏是有序的，就没有给收藏夹应用这个设置。如果要给它应用的话或许还要加一个是否覆盖原有排序的开关

feat: Optimized the sorting function of the librarybar

---

src/renderer/src/pages/Record/WeeklyReport.tsx
src/renderer/src/stores/game/recordUtils.ts

- 在月度报告中，星期日被当作了一周的第一天，将其修改为了周一
- 在周度报告中，能否切换到下一周的判断有误，在周日就可以切换到下一周（因为判断用的weekEnd实际上是最后一天的开始而不是结束）
- 在周度报告中，使用上游函数传递过来的日期字符串初始化Date对象时，`Date(str)`错误地将本地时区的日期初始化为了UTC对应日期的0点，在负数时区中会导致日期的错位

fix: Fixed the wrong time zone conversion and week calculation on the record page

---

src/renderer/src/components/Showcase/Collections.tsx
src/renderer/src/components/Showcase/posters/CollectionPoster.tsx
src/renderer/src/components/Showcase/posters/GamePoster.tsx
src/renderer/src/pages/DragContainer.tsx

优化了拖拽相关的若干样式问题：
1. 对于从外部添加文件的拖拽功能，添加了过滤条件，避免软件内部拖拽事件触发阴影蒙版
2. 对于主页中收藏夹的拖拽排序，修复了因为gap值调整而歪掉不在正中间的拖拽指示器
3. 优化了收藏夹海报与游戏海报的拖拽预览样式，使其能够透出下方背景

fix: Optimized drag-and-drop display

---

src/renderer/src/components/Showcase/CollectionGames.tsx
src/renderer/src/components/Showcase/posters/GamePoster.tsx

主要修复展示某一收藏中游戏海报时的样式问题：
- 最底部一行的海报无法显示完全，存在小部分遮挡
- 修改了海报尺寸后没有同步修改预览样式的尺寸，导致其稍大一圈，在显示时会在纵向挤开其他行

fix: Optimized display in the games-of-collection page

---

src/renderer/locales/en/scanner.json
src/renderer/locales/en/transformer.json
src/renderer/locales/zh-CN/scanner.json
src/renderer/locales/zh-CN/transformer.json
src/renderer/src/pages/GameScannerManager/FailedFoldersDialog.tsx
src/renderer/src/pages/GameScannerManager/GameScannerListItem.tsx
src/renderer/src/pages/TransformerManager/TransformerItem.tsx

添加了扫描器的提示：
- 对主页面三个没有文字的按钮，增加了悬浮提示
- 对纠错弹窗中的路径与错误信息，因为可能被省略，增加了悬浮提示
- 将修复弹窗中的错误信息换成了红色，增加对比度
添加了转换器的提示：
- 对主页面三个没有文字的按钮，增加了提示
> 语言文件加起来好麻烦，先空着到时候去网站上整好了

Optimize tooltips

---

src/renderer/locales/en/transformer.json
src/renderer/locales/zh-CN/transformer.json
src/renderer/src/pages/TransformerManager/RuleDialog.tsx

虽然已经用`react-window`把虚拟列表加上了，也能生效，但是渲染方面还有一些问题：
如果用`scrollbar-base`这些自定义的滑块样式，渲染的内容就会模糊（下有gif），原生的滑块就没问题
~~总之在考虑要不要换个虚拟列表的库试试（~~
**喜报，找到相关的issue与解法了**：https://github.com/bvaughn/react-window/issues/560

Optimize transformer manager‘s rule dialog

---

src/renderer/locales/en/sidebar.json
src/renderer/locales/it/sidebar.json
src/renderer/locales/ja/sidebar.json
src/renderer/locales/ko/sidebar.json
src/renderer/locales/zh-CN/sidebar.json
src/renderer/locales/zh-TW/sidebar.json
src/renderer/src/components/Game/Header.tsx
src/renderer/src/components/Game/main.tsx
src/renderer/src/components/Librarybar/GameNav.tsx
src/renderer/src/components/Showcase/posters/BigGamePoster.tsx
src/renderer/src/components/Showcase/posters/CollectionPoster.tsx
src/renderer/src/components/Showcase/posters/GamePoster.tsx
src/renderer/src/components/Titlebar.tsx
src/renderer/src/pages/Light.tsx
src/renderer/src/pages/Record/GameRankingItem.tsx
src/renderer/src/pages/Record/ScoreReport.tsx
src/types/models/config.ts

弃用了原先boolean类型的enableNSFWBlur配置字段，使用新的枚举字段记录屏蔽级别，目前共三个级别：不屏蔽 / 屏蔽图片 / 屏蔽图片与标题。
> 隐藏游戏先画个饼在那放着

feat: add tiered NSFW content filtering

---

src/renderer/src/components/Librarybar/GameNav.tsx

可变游戏列表的宽度计算忽略了本地游戏标记的宽度，导致该图标渲染位置错误。

fix: correct rendering of local game icon that was outside the visible area

---

src/renderer/locales/en/game.json
src/renderer/locales/ja/game.json
src/renderer/locales/zh-CN/game.json
src/renderer/locales/zh-TW/game.json
src/renderer/src/components/Game/Config/ManageMenu/PlayTimeEditorDialog.tsx
src/renderer/src/components/Game/Record/ChartCard.tsx
src/renderer/src/components/ui/input.tsx

这是关于 #348 中提及问题的一个临时补丁，在新版游玩时间编辑器的保存过程中保留了之前设置的未被计时器追踪的游玩时间信息，同时支持对该部分时间进行独立设定。

fix: preserve legacy fuzzy play time in play time editor

---

src/renderer/src/app/router.tsx
src/renderer/src/components/Game/Record/TimerChart.tsx
src/renderer/src/pages/Config/main.tsx
src/renderer/src/pages/Record/MonthlyReport.tsx
src/renderer/src/pages/Record/WeeklyReport.tsx
src/renderer/src/pages/Record/YearlyReport.tsx
src/renderer/src/pages/Record/main.tsx

**重构了 Record 页结构**：
- 将 Tab 状态与当前查询日期状态提升到路由查询参数中，统一通过 URL 控制页面状态，以实现记录页内部的前进后退导航与各报告的查询值共享
- 调整年报 / 月报 / 周报 Tab 的排列顺序，以提升切换不同报告项时的体验
- 月报图表由原先的周数据改为展示每日数据
**新增了 Record 页内部的快捷跳转功能**：
- 点击年报图表项 → 跳转到对应月报
- 点击月报图表项 → 跳转到对应周报
- 点击游戏时长图表项 → 跳转到对应周报
**其他**：
类似于对记录页的路由修改，将设置页的 Tab 状态提升到路由查询参数，确保返回页面时能够恢复上次的 Tab 选择（Fixes #333 ）

Opti: navigation in record page (settings page)

---

src/renderer/src/components/Showcase/posters/BigGamePoster.tsx
src/renderer/src/components/Showcase/posters/GamePoster.tsx
src/renderer/src/components/Showcase/posters/PlayButton.tsx

加强了主页海报快速游玩按钮的视觉提示，以避免误触。
> 目前按钮在鼠标悬停时不仅有透明度变化，还会伴随尺寸改变。

feat(poster): improve visual feedback of quick-play button

---

src/renderer/locales/en/game.json
src/renderer/locales/zh-CN/game.json
src/renderer/src/components/Game/Config/Properties/Media/ImageViewerDialog.tsx
src/renderer/src/components/Game/Config/Properties/Media/main.tsx
src/renderer/src/components/Game/Config/Properties/Path/main.tsx
src/renderer/src/components/Game/Config/Properties/main.tsx
src/renderer/src/components/Game/Header.tsx
src/renderer/src/components/Game/HeaderCompact.tsx
src/renderer/src/components/Game/Memory/MemoryCard.tsx
src/renderer/src/components/Game/Memory/main.tsx
src/renderer/src/components/Game/main.tsx
src/types/models/game.ts

- 支持设置和管理游戏的截图保存路径  
- 在“回忆”界面中添加一键打开截图路径的按钮，方便快速访问截图文件夹
- 在游戏详情页新增 **编辑媒体属性** 和 **查看大图** 右键菜单，便于快速修改媒体信息
- 允许在大图模式下复制或保存图片

新增游戏媒体管理功能：截图路径管理、大图查看与右键编辑菜单
