package-lock.json
src/renderer/src/components/AddGame.jsx
src/renderer/src/components/scraper.mjs

1. 为游戏名识别游戏后添加选择提示。此外，当只有一个游戏待选时也可以不选择。 Fixes #71 
2. 修改调用VNDB API获取背景、封面、vid的方法，修复绝大多数的游戏数据不匹配问题。 Fixes #65 
3. 修复选择背景界面的提示不能正常显示的问题。
4. 修复刮削器不输入任何信息点击识别也会转圈的问题。
PS. 因为我不用云存档，所以相关的bug估计是不会修了。我自己能用到的部分bug应该都修的差不多了hhh。
PPS. 坐等大佬的2.0版本，快端上来罢，期待ing

Many fixes

---

src/renderer/src/components/Showcase/posters/BigGamePoster.tsx
src/renderer/src/components/Showcase/posters/GamePoster.tsx

将一些东西搬从 `HoverCardTrigger` 里搬出，解决了 `HoverCard` 不正常存在的问题。

Fix HoverCard 

---

src/renderer/src/components/Librarybar/GameList/Collection.tsx
src/renderer/src/components/Librarybar/GameList/FilterGame.tsx
src/renderer/src/components/Librarybar/GameList/Others.tsx
src/renderer/src/components/Librarybar/GameList/Search.tsx
src/renderer/src/components/Librarybar/main.tsx
src/renderer/src/components/Showcase/AllGames.tsx

使游戏列表长度能自适应界面高度变化
使游戏墙的海报间距自适应界面宽度变化

Make the GameList and GamePoster adaptive

---

src/renderer/src/pages/GameAdder/ScreenshotList.tsx

在添加游戏入库时，阻止重复点击造成添加多个游戏项目。
与 #92 有关

Check for duplicate clicks when adding game

---

src/renderer/src/components/Config/Theme.tsx
src/renderer/src/components/Config/main.tsx
src/renderer/src/pages/Record/main.tsx

1. 修复Record界面海报变形的问题
2. 修复小尺寸下设置页面及其主题页显示不全的问题

fix themeConfig and recordPoster

---

src/renderer/src/components/Game/Config/AttributesDialog/Media/main.tsx
src/renderer/src/components/Game/Config/AttributesDialog/main.tsx

Fix AttributesDialog on small size

---

src/renderer/src/components/Showcase/CollectionPage.tsx
src/renderer/src/components/Showcase/Collections.tsx
src/renderer/src/components/Showcase/posters/CollectionPoster.tsx
src/renderer/src/components/contextMenu/CollectionCM/main.tsx

1. 点击收藏菜单中的选项后自动关闭菜单
2. 修改了似乎是拼写错误的 `collctionId`

Move Dialog to automatically close CollectionCM

---

package.json
src/renderer/src/components/Game/Config/ManageMenu/PlayingTimeEditorDialog.tsx

- 引入了包`expr-eval`用于计算表达式字符串
- 支持在修改游戏时间界面使用四则运算表达式进行输入
- 支持回车作为快捷键完成确认操作

Support expression evaluation and shortcuts in `PlayingTImeEditorDialog`

---

package-lock.json
package.json
src/renderer/src/pages/Record/PlayedTimesRank.tsx
src/renderer/src/pages/Record/PlayingTimeRank.tsx
src/renderer/src/pages/Record/ScoreRank.tsx
src/renderer/src/pages/Record/main.tsx

为 `Record` 页面的三个排行使用了虚拟列表，优化游戏数量大时 `Record` 页面渲染

Use VirtualList for the Rank on Record

---

src/renderer/src/components/Game/Save/main.tsx

Display game saves in descending order by date

---

src/renderer/src/components/Showcase/CollectionGames.tsx
src/renderer/src/components/Showcase/posters/CollectionPoster.tsx
src/renderer/src/components/Showcase/posters/GamePoster.tsx
src/renderer/src/components/ui/drop-indicator.tsx
src/renderer/src/hooks/collections.ts
src/renderer/src/utils/dnd-utills.ts

- 优化了拖拽提示器的样式
- 添加了通过拖拽重新排序收藏夹内游戏顺序的功能
- 修复了收藏夹名称过长时文字溢出的问题

Support reorder games in collection with drag-and-drop

---

src/main/database/save.ts
src/renderer/src/components/Game/Config/AttributesDialog/Path/main.tsx
src/renderer/src/components/Game/Save/main.tsx

- 增加了为每个游戏单独设置最大存档备份数量的功能（仅在游戏结束时触发备份删除逻辑） #153
- 增加了锁定某个存档备份的功能（锁定的存档不计入数量）
- 修复了添加游戏存档路径时可能会出现空行的问题

Optimize game save management

---

src/renderer/src/components/Showcase/AllGames.tsx
src/renderer/src/components/Showcase/CollectionGames.tsx
src/renderer/src/components/Showcase/CollectionPage.tsx
src/renderer/src/components/Showcase/Collections.tsx
src/renderer/src/components/Showcase/RecentGames.tsx

为 收藏页 的 收藏 和 收藏的游戏 也使用 grid 布局

Use grid to optimize UI

---

src/renderer/src/components/Config/General.tsx
src/renderer/src/components/ThemeProvider.tsx

Theme light/dark can follow system

---

src/renderer/src/components/Showcase/posters/GamePoster.tsx
src/renderer/src/pages/Record/main.tsx

- 优化了记录页面四个大卡片的长游戏名显示
- 优化了拖拽游戏时预览卡片中的游戏名样式

Optimized the display of long game names

---

src/renderer/src/pages/Record/ScoreReport.tsx

解决：#185 
> 查了半天刚编个差不多那头就提出来issue了

fix: native scrollbar appears on scoreReport page with too many items

---

src/renderer/locales/en/game.json
src/renderer/locales/ja/game.json
src/renderer/locales/zh-CN/game.json
src/renderer/src/components/Game/Header.tsx
src/renderer/src/components/Game/Overview/RelatedSites/RelatedSitesCard.tsx

- 为 修改评分/修改游戏状态 的按钮增加了提示
- 修改了相关网站的提示弹出方向，避免遮挡

feat: Optimized the tooltips in the game overview page

---

src/renderer/src/components/Librarybar/GameList/Others.tsx
src/renderer/src/components/Librarybar/SortMenu.tsx
src/renderer/src/components/Librarybar/main.tsx

将按游玩状态分组时，调整游玩状态顺序的入口从右键菜单移动到了外面

feat: Optimized the function of adjusting the display order of playStatus in the librarybar

---

src/renderer/locales/en/config.json
src/renderer/locales/ja/config.json
src/renderer/locales/zh-CN/config.json
src/renderer/locales/zh-TW/config.json
src/renderer/src/Setup.tsx
src/renderer/src/pages/Config/Hotkeys.tsx
src/renderer/src/pages/Config/main.tsx
src/types/database/config.ts

- 增加了快捷键，用于导航至 前/后一个页面
- 为设置页面增加了返回按钮

Optimize back/forward navigation (hotkeys and config page)

---

src/main/launcher/services.ts
src/renderer/locales/en/config.json
src/renderer/locales/ja/config.json
src/renderer/locales/zh-CN/config.json
src/renderer/locales/zh-TW/config.json
src/renderer/src/pages/Config/General.tsx
src/types/database/config.ts

feat: Make minimize-to-tray after game launch configurable

---

src/renderer/locales/en/config.json
src/renderer/locales/en/game.json
src/renderer/locales/en/sidebar.json
src/renderer/locales/zh-CN/config.json
src/renderer/locales/zh-CN/game.json
src/renderer/locales/zh-CN/sidebar.json
src/renderer/src/components/Game/Config/ManageMenu/main.tsx
src/renderer/src/components/Game/main.tsx
src/renderer/src/components/Showcase/posters/BigGamePoster.tsx
src/renderer/src/components/Showcase/posters/CollectionPoster.tsx
src/renderer/src/components/Showcase/posters/GamePoster.tsx
src/renderer/src/components/Sidebar.tsx
src/renderer/src/components/contextMenu/GameNavCM/ManageMenu.tsx
src/renderer/src/components/ui/game-image.tsx
src/renderer/src/pages/Config/Appearances.tsx
src/types/database/config.ts
src/types/database/game.ts

实现#234 中的NSFW相关功能。
- 游戏：添加了nsfw字段进行标识
- 是否在侧边栏显示切换按钮
- 是否屏蔽NSFW内容

feat: Support for NSFW content blocking

---

src/renderer/src/pages/Record/WeeklyReport.tsx
src/renderer/src/stores/game/gameUtils.ts
src/renderer/src/stores/game/recordUtils.ts

Fix record display issue related to negative time zones

---

src/renderer/src/stores/game/gameUtils.ts

fix: incorrect total played days calculation across multiple games

---

src/renderer/locales/en/adder.json
src/renderer/locales/en/config.json
src/renderer/locales/en/scanner.json
src/renderer/locales/en/transformer.json
src/renderer/src/pages/Config/Appearances.tsx
src/types/database/config.ts

i18n: add pluralization support for English translations

---

.gitignore
src/renderer/src/components/ui/drop-indicator.tsx

fix: drop indicator does not work

---

.gitignore
package-lock.json
src/main/features/adder/services/scanner.ts
src/main/index.ts
src/renderer/locales/en/game.json
src/renderer/locales/zh-CN/game.json
src/renderer/src/components/Game/Config/ManageMenu/DeleteGameAlert.tsx
src/renderer/src/components/GameBatchEditor/BatchGameNavCM/DeleteGameAlert.tsx
src/renderer/src/pages/GameScannerManager/FailedFoldersDialog.tsx
src/renderer/src/pages/GameScannerManager/GlobalSettingsDialog.tsx

修复：扫描器忽略列表不起作用的问题
优化：扫描器列表项目去重并按字母表排序
新功能：删除游戏时可选择是否将游戏目录也加入到忽略列表中，避免删除后被扫描器再次扫描到

fix: scanning ignore list is not taken effect

---

src/renderer/src/pages/Record/MonthlyReport.tsx

- 将月度报告中的日历高亮改为热力图
- 去掉了日历中的`selected={selectedDate}`，在从年度报告导航至月度报告时其会导致高亮错误

feat(record page): highlight calendar as heatmap in monthly report

---

src/renderer/src/components/Game/Save/main.tsx

尝试修复#358，主要是v4升级后遗漏了一处函数调用的修改。
> 在我本地复现出的问题与其报告并不完全一致

fix(save management): lock state changes not persisted
